### ISSUE TITLE
Maze Not drawing Properly 

### ISSUE THREAD

**Issue by Rishiraj2594** [Rishiraj2594/MazeGen#2]
At low wall thickness ex `const float WALL_THICKNESS = BLOCK_SIZE*0.01;`
Maze grids are merging and not drawing properly
For 10 * 10 grid here is the result

<img width="600" alt="Screenshot 2024-07-03 at 1 11 12 AM" src="https://github.com/Rishiraj2594/MazeGen/assets/78264424/5b4260c0-8c40-4b83-8cd1-8b226d1f7b4a">

**Comment by Pushpender-18** [comment]
Formula has some issue as well as the thickness cannot be 0.5 pixels so I think we should just avoid this by setting the data type of WALL_THICKNESS to int

**Comment by Rishiraj2594** [comment]
Go ahead with your fix
